# Generated by Django 3.1.2 on 2021-03-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_theme', to='articles.article')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статей',
                'ordering': ['-main', 'theme__theme'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(unique=True, verbose_name='Название')),
                ('articles', models.ManyToManyField(blank=True, related_name='scopes', through='articles.ArticleScope', to='articles.Article')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='articlescope',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_article', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
