# Generated by Django 3.1.2 on 2021-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210315_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='theme',
            field=models.TextField(unique=True, verbose_name='Категория'),
        ),
    ]
